### PR TITLE
Copy onlyNewer files.

### PR DESCRIPTION
**Pull request by bmustiata**
Adds the option of copying only newer files.

### CODE REVIEW

**Comment by ctalkington** [comment]
i think this type of feature has been passed on before, dont recall an issue id, but grunt-newer might be of use here.

https://github.com/tschaub/grunt-newer

**Comment by bmustiata** [comment]
Well it was this one (which in my opinion was pretty much perfect):
https://github.com/gruntjs/grunt-contrib-copy/pull/56

But then this was closed in hoping of:
https://github.com/gruntjs/grunt/issues/694

Which was also shut down.

Also this was there along the way, with the same fate:
https://github.com/gruntjs/grunt-contrib-copy/pull/159

Now I understand that I could use that extra plugin to do this, but for the
love of God, why? I could use grunt-sync directly, why bother?

Everyone expects copy to have the update option, that's why people ask
about it:
https://www.npmjs.com/package/grunt-sync
https://www.npmjs.com/package/dp-grunt-contrib-copy
http://stackoverflow.com/questions/16545167/gruntjs-how-to-make-copy-task-to-copy-only-changed-files-on-watch

(copy man page: http://unixhelp.ed.ac.uk/CGI/man-cgi?cp)

I thought it to be a sort of self evident thingie, and I was baffled it's
not in the grunt-contrib-copy.

**Comment by sindresorhus** [comment]
:-1: Just use grunt-newer.

**Comment by bmustiata** [comment]
Look... there already is grunt sync that does both, I don't need to use a
non contrib plugin AND a contrib one.

I can also just rebrand my fork and use that one, it's literally 10 minutes
of work.

Feel free to close this issue, but I seriously don't understand your
reasoning. As I said before, I thought having the update option in the copy
task to be self evident, but if you guys deem it unnecessary than so be it.

**Comment by ctalkington** [comment]
adding such a feature adds the requirement of maintaining it for the people who already graciously volunteer their time to make these tasks.

also in most cases, you going to want to use `newer` logic for more than just copying so it doesn't make since for every task to re-implement it under a million different option names.

just my two cents on the matter.

**Comment by bmustiata** [comment]
Man... seriously.

Rage mode: ON

On one hand the maintenance costs are negligible at best. Look at the actual code and what it does. That's why I even added the test. There is stuff to copy the timestamp of the files in there. I can argue that's "far" more complex. 

On the other hand chit-chat regarding the issue, even with proposed implementations, is since February 2013. That's over two years ago. Two years. Years! For a feature that people actively want. Generally everyone agrees that "something" should be done, but it's proposed implementations are never good enough, doesn't catches all the finer aspects, etc.

And if ever the grunt core will add the "standard" version, wouldn't then make sense just to in a first stage deprecate this option, then remove it? That's why versions exist in the first place, aren't they? What do you want, to wait two more years for the perfect idea to come up? First in the core of course, because it belongs there, and then slowly creep into other plugins?

Meanwhile the best practice is apparently to use another plugin, because copy can't handle this basic usage. But that's not a problem, that's just how the things should be done until the perfect solution will be found.

Right.

Rage mode: OFF

This is my last comment on the issue, since I feel that we have a serious mismatch in how we see this issue, and I don't think commenting more, at least from my side, adds value to the discussion. As said before, feel free to close it.

**Comment by stevemao** [comment]
@bmustiata you might wanna read
https://github.com/substack/browserify-handbook#module-philosophy
and
https://github.com/substack/node-mkdirp/issues/17

**Comment by masi** [comment]
Cannot see why that should be hard to maintain. How can I help to add this feature?

BTW standard Unix "cp --update" does the trick on a lower level, so there have been folks who have long ago have asked for such a feature.

As for grunt-newer:

https://github.com/tschaub/grunt-newer/issues/84
https://github.com/tschaub/grunt-newer/issues/86

So no luck with that.

**Comment by bmustiata** [comment]
@masi You can use `grunt-sync`. This is what I currently use.

**Pull request closed without merging**
