### PR TITLE
Add check for syncTimestamp based on relevant option

### LINKED ISSUE #287: syncTimestamp running even if timestamp option is false
My timestamp option is not set, so it should be `false`. However, `syncTimestamp` is being called, which results in a `Warning: EPERM: operation not permitted, futime Use --force to continue.` since the user running `grunt` does not own the destination files, but is a member of the same group as the owning users and has write access.

### PR DESCRIPTION
**Pull request by relaxatorium**
Fixes #287 

Still needs proper tests, but starting the request now to get the ball rolling.

### CODE REVIEW

**Comment by relaxatorium** [comment]
It says I signed the agreememt here (https://cla.js.foundation/gruntjs/grunt-contrib-copy?pullRequest=290), but the CLA-bot's check seems to disagree.

**Comment by XhmikosR** [comment]
The patch has unrelated changes.

**Comment by XhmikosR** [comment]
Also, I'm not sure if the change is right or not.

```
timestamp

Type: Boolean
Default: false

Whether to preserve the timestamp attributes(atime and mtime) when copying files. Set to true to preserve files timestamp. But timestamp will not be preserved when the file contents or name are changed during copying.
```

/CC @vladikoff to chime in.

**Comment by mcnicholls** [comment]
This change does seem to fix the issue with timestamp preservation (#287)
Current behaviour doesn't match the documentation, but after applying this fix it does.

Can this be progressed or does a new PR need opening?

I'm happy to address this if I can as it's causing me issues with grunt-newer.

**Comment by mcnicholls** [comment]
Thanks 😀

When will a new version be available via npm with this fix?

**Comment by XhmikosR** [comment]
@mcnicholls: I don't have npm push rights, so only @vladikoff can cut a new release.

**Comment by LC43** [comment]
Hi, any time frame for a new release? i used the latest code and it fixes the issue #287 that i also had.

**Pull request merged**
