### PR TITLE
Bump devDependencies.

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @shama

### CODE REVIEW

**Comment by shama** [comment]
Thanks!

**Comment by XhmikosR** [comment]
Maybe we should cut a new release?

**Comment by vladikoff** [comment]
Yeah let's ship 1.0.0

**Comment by shama** [comment]
We'll need to add `"peerDependencies": { "grunt": ">=0.4.0" }` for consistency.

Also are there any easy wins in the PRs or issues? Out of date dependencies or CI configs? I've been quickly checking for those things getting each up to 1.0.0.

**Comment by XhmikosR** [comment]
@shama: https://github.com/gruntjs/grunt-contrib-internal/commit/07d794715146d8edd5a3239283cbf6be4c5ac095#commitcomment-16317993

Then we can easily update CI configs.

**Comment by shama** [comment]
I want to get the `package.json` normalizations into `grunt-contrib-internal` first before bumping and applying to the plugins (I should have some time this weekend).

**Pull request merged**
